use_frameworks!

platform :ios, '8.0'

target 'INetworkPacketParser_Example' do
  pod 'INetworkPacketParser', :path => '../'

  target 'INetworkPacketParser_Tests' do
    inherit! :search_paths

    
  end
end
